/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

public class App {
public static void main(String[] args) {
       
        aluno aluno = new aluno("arthur",03,"ensino medio");
        livro livro  = new livro("pint", "gots",87);
        produto produto = new produto("gatta",89,7);

        
        aluno.apresentar();
        livro.livros();
        produto.prod();
}
}
